# #####
# define.py: 전역 상수가 저장되어 있는 파일.
# #####

# ---
# 상수 정의
# ---
WINDOW_WIDTH, WINDOW_HEIGHT = 1280, 960

BOARD_WIDTH, BOARD_HEIGHT = 800, 400
BOARD_X, BOARD_Y = 240, 280

BALL_SIZE = 18
BALL_COLOR_WHITE, BALL_COLOR_YELLOW, BALL_COLOR_RED = 0, 1, 2
BALL_ACCEL = -1

CUE_WIDTH, CUE_HEIGHT = 337, 21

# ball Speed
PIXEL_PER_METER = 3.555 * 0.001  # 1 pixel 3.555 mm
METER_PER_PIXEL = 1 / PIXEL_PER_METER

# # Boy Action Speed
# TIME_PER_ACTION = 0.5
# ACTION_PER_TIME = 1.0 / TIME_PER_ACTION
